name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - development
jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: SGS

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
        
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r SGS/requirements.txt
          pip install pylint black pytest

      - name: Format Lambda function
        run: |
          black SGS/ tests/

      - name: Lint Lambda function
        run: |
          pylint --disable=R,C SGS/ tests/

      - name: Run tests
        run: |
          pytest tests/  

  Build:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.3.0

      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Build SAM application
        run: |
          sam build --use-container

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.3.0

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy SAM application
        env:
          AWS_DEFAULT_REGION: sa-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          sam deploy --resolve-s3 --stack-name sgs-stack-dev --region sa-east-1 --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides Environment=development