name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
        
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.3.0
        
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r SGS/requirements.txt
          pip install pylint black pytest

      - name: Format Lambda function
        run: |
          black SGS/ tests/

      - name: Lint Lambda function
        run: |
          pylint --disable=R,C SGS/ tests/

      - name: Build Lambda function
        run: sam build
