name: Zip function to upload

on: [push]

jobs:
  zip-repo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Zip repository contents
        run: |
          zip -r function.zip . -x ".*" -x "*/.*" -x "function.zip"

      - name: Upload function.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-zip
          path: function.zip
